version: '3.7'
services:

  dtl-main:
    image: puyuantech/cryptofx:latest
    container_name: dtl-main
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 1 G
    command: >
        bash -c "gun start master &&
                 /bin/bash"
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log
      # - ./etc/md_test.py:/shared/md_test.py

  dtl-market:
    image: puyuantech/cryptofx:latest
    container_name: dtl-market
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 2 G
    command: >
        bash -c "gun start mr -f market1 &&
                 /bin/bash"
    depends_on:
      - dtl-main
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-trade:
    image: puyuantech/cryptofx:latest
    container_name: dtl-trade
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.5'
          memory: 3 G
    command: >
        bash -c "gun start tr -f trade1 &&
                 /bin/bash"
    depends_on:
      - dtl-main
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-oms:
    image: puyuantech/cryptofx:latest
    container_name: dtl-oms
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 2 G
    command: >
        bash -c "sleep 1 &&
                 gun start oms -f oms1 -r trade1 -d &&
                 /bin/bash"
    depends_on:
      - dtl-trade
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-mg_binance:
    image: puyuantech/cryptofx:latest
    container_name: dtl-mg_binance
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 200 M
    command: >
        bash -c "sleep 1 &&
                 gun start mg -g binance -p cryptofx &&
                 /bin/bash"
    depends_on:
      - dtl-market
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-mg_bitmex:
    image: puyuantech/cryptofx:latest
    container_name: dtl-mg_bitmex
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 200 M
    command: >
        bash -c "sleep 1 &&
                 gun start mg -g bitmex -p cryptofx &&
                 /bin/bash"
    depends_on:
      - dtl-market
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-mg_huobi:
    image: puyuantech/cryptofx:latest
    container_name: dtl-mg_huobi
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 200 M
    command: >
        bash -c "sleep 1 &&
                 gun start mg -g huobi -p cryptofx &&
                 /bin/bash"
    depends_on:
      - dtl-market
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-mg_okex:
    image: puyuantech/cryptofx:latest
    container_name: dtl-mg_okex
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 200 M
    command: >
        bash -c "sleep 1 &&
                 gun start mg -g okex -p cryptofx &&
                 /bin/bash"
    depends_on:
      - dtl-market
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  dtl-mgs:
    image: puyuantech/cryptofx:latest
    container_name: dtl-mgs
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 600 M
    command: >
        bash -c "sleep 1 &&
                 gun start mg -g bitstamp -p cryptofx &&
                 gun start mg -g coinbase -p cryptofx &&
                 gun start mg -g kraken -p cryptofx &&
                 /bin/bash"
    depends_on:
      - dtl-market
    volumes:
      - ./etc/config.json:/shared/etc/config.json
      - ./log:/shared/log

  # dtl-tgs:
  #   image: puyuantech/cryptofx:latest
  #   container_name: dtl-tgs
  #   network_mode: "host"
  #   tty: true
  #   stdin_open: true
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 3
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 4 G
  #   command: >
  #       bash -c "sleep 2 &&
  #                gun start tg -g binance -a tg1 -p cryptofx &&
  #                gun start tg -g bitmex -a tg2 -p cryptofx &&
  #                /bin/bash"
  #   depends_on:
  #     - dtl-trade
  #   volumes:
  #     - ./etc/config.json:/shared/etc/config.json
  #     - ./log:/shared/log
